name: Build and Push to Registry
on:
  push:
    branches:
      - main
    paths:
      - 'backup/Dockerfile'
      - 'backup/hooks/**'
      - '.forgejo/workflows/**'

jobs:
  build-backup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Codeberg Registry
        uses: https://github.com/docker/login-action@v3
        with:
          registry: codeberg.org
          username: ${{ forgejo.repository_owner }}
          password: ${{ secrets.REGISTRY_TOKEN }}

      - name: Build and push backup image
        uses: https://github.com/docker/build-push-action@v5
        with:
          context: backup
          push: true
          tags: |
            codeberg.org/${{ forgejo.repository }}/pbs-mailcow:latest